### ISSUE TITLE
BrowserModule has already been loaded

### ISSUE THREAD

**Issue by tsafadi** [mazid1/ngx-mzd-timeline#2]
I keep getting an error that the BrowserModule is already implemented:

`ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.`

**Comment by tsafadi** [comment]
I believe there is an open pull request that addresses this issue.

**Comment by mazid1** [comment]
I have merged the PR and published v1.0.2. Please let me know if that fixed your problem. If it is fixed, then we can close this issue.

**Comment by mazid1** [comment]
Fixed in #1
